version: "3.7"

services:
  
  gitea:
    container_name: gitea
    image: gitea/gitea:latest
    restart: unless-stopped
    networks:
      - traefik-network
    volumes:
      - ${GITEA_DATA}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - RUN_MODE=prod
      - DISABLE_SSH=true
      - HTTP_PORT=3000
      - ROOT_URL=https://git.${DOMAIN}
      ## Uncomment these after installation
      #- INSTALL_LOCK=true
      #- SECRET_KEY=${SECRET}
      #- DISABLE_REGISTRATION=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.entrypoints=web
      - traefik.http.routers.gitea.rule=Host(`git.${DOMAIN}`)
      - traefik.http.routers.gitea.middlewares=basic-http
      - traefik.http.routers.gitea-sec.entrypoints=websecure
      - traefik.http.routers.gitea-sec.rule=Host(`git.${DOMAIN}`)
      - traefik.http.services.gitea-sec.loadBalancer.server.port=3000
      - traefik.http.routers.gitea-sec.middlewares=basic
      - traefik.http.routers.gitea-sec.tls=true
      - traefik.http.routers.gitea-sec.tls.certresolver=cfdns

networks:
  traefik-network:
    external: true
  default:
    driver: bridge